version: "2"
services:
  web:
    build: .
    command: bash -c "npm link gulp gulp-postcss postcss-import postcss-cssnext cssnano && gulp css && gulp server"
    ports:
      - "1313:1313"
    volumes:
      - .:/asturiashacking
