name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: "npm install"
      - uses: cypress-io/github-action@v2
        with:
          command: "npm run ci:test"
